[package]
name = "cve-get"
version = "0.1.0"
authors = ["Darth-Revan <S1610304005@students.fh-hagenberg.at>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
curl = "0.4"
chrono = {version = "0.4", features = ["serde"]}
